version: "3"

services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    restart: always
    networks:
      - "front_net"
    volumes:
      - "./doc:/usr/share/nginx/html/doc"
    environment:
      API_URL: doc/openapi.yaml
    ports:
      - "80:8080"

networks:
  front_net:
    external: true
