version: "3"

services:
  swagger:
    image: my-swagger-ui
    container_name: swagger_ui
    restart: always
    networks:
      - "front_net"
    environment:
      API_URL: /doc/openapi.yaml

networks:
  front_net:
    external: true
